server:
  port: 8080

spring:
  application:
    name: backend-service
  profiles:
    active: @spring.profiles.active@ # lấy giá trị từ file pom.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        include: health,prometheus,metrics

logging:
  level:
    root: INFO
    web: INFO

